name: Docker Image CI

on:
  push:
    branches:
      - master
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/adamsong/cursedbot/CursedBot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
